<#
.SYNOPSIS
  Builds, installs or removes Tumble's Windows 11 top-level context menu.

.DESCRIPTION
  The menu is tumble_explorer.dll (an IExplorerCommand handler) registered
  by a sparse MSIX package whose files stay in the folder that holds
  tumblew.exe. The classic "Show more options" menu from
  `tumble menu install` must be installed first: this menu reads it.

    build      Builds the DLL, copies it next to tumblew.exe, writes the
               package manifest and logos, packs and signs the MSIX with a
               self-signed certificate. Touches no certificate store and no
               registry; makes no network calls.

    install    (Run yourself, in an elevated terminal.) Trusts the
               certificate for package installs (LocalMachine\TrustedPeople),
               then registers the package for your user.

    uninstall  Removes the package, and the certificate if elevated.

  Output: dist\explorer-menu\ in the repository.

.PARAMETER AppDir
  Folder with tumblew.exe. Defaults to the one `tumble menu install`
  registered.
#>
param(
    [Parameter(Mandatory)][ValidateSet('build', 'install', 'uninstall')][string]$Action,
    [string]$AppDir
)
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repo = Resolve-Path (Join-Path $PSScriptRoot '..\..\..')
$out = Join-Path $repo 'dist\explorer-menu'
$msix = Join-Path $out 'tumble-explorer-menu.msix'
$cer = Join-Path $out 'tumble-dev.cer'
$pfx = Join-Path $out 'tumble-dev.pfx'
$packageName = 'Tumble.ExplorerMenu'
$publisher = 'CN=Tumble Dev'
$clsid = '7c1e2b9a-4f0d-4c55-9a63-2d8e5b1f0a47'   # tumble_explorer::CLSID
$sdk = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin\*\x64\makeappx.exe' |
    Sort-Object FullName -Descending | Select-Object -First 1 | ForEach-Object DirectoryName

if (-not $AppDir) {
    $registered = (Get-ItemProperty 'HKCU:\Software\Classes\Tumble' -ErrorAction SilentlyContinue).Tumblew
    if (-not $registered) { throw 'Run `tumble menu install` first; this menu builds on it.' }
    $AppDir = Split-Path $registered
}
if (-not (Test-Path (Join-Path $AppDir 'tumblew.exe'))) { throw "tumblew.exe not found in $AppDir" }

function Build {
    New-Item -ItemType Directory -Force $out | Out-Null
    Write-Host '== building tumble_explorer.dll'
    Push-Location (Join-Path $repo 'apps\explorer')
    try {
        cargo build --release
        if ($LASTEXITCODE -ne 0) { throw 'cargo build failed' }
    }
    finally { Pop-Location }
    Copy-Item (Join-Path $repo 'apps\explorer\target\release\tumble_explorer.dll') $AppDir -Force

    Write-Host '== package layout'
    $pkg = Join-Path $out 'package'
    if (Test-Path $pkg) { Remove-Item -Recurse -Force $pkg }
    New-Item -ItemType Directory -Force (Join-Path $pkg 'Assets') | Out-Null
    $tumble = Join-Path $AppDir 'tumble.exe'
    $logo = Join-Path $repo 'assets\tumble.png'
    foreach ($l in @(@('Square150x150Logo', 150), @('Square44x44Logo', 44), @('StoreLogo', 50))) {
        $tmp = Join-Path $out ("{0}.png" -f $l[0])
        Copy-Item $logo $tmp -Force
        & $tumble $tmp --to png --resize $l[1] -o (Join-Path $pkg 'Assets') --overwrite | Out-Null
        Move-Item -Force (Join-Path $pkg ("Assets\{0} (1).png" -f $l[0])) (Join-Path $pkg ("Assets\{0}.png" -f $l[0])) -ErrorAction SilentlyContinue
        Remove-Item $tmp
    }

    # One ItemType per extension Tumble knows; the command hides itself for
    # types with no targets on this PC.
    $exts = (& $tumble formats --json | ConvertFrom-Json) | ForEach-Object { $_.extensions } | Sort-Object -Unique
    $itemTypes = ($exts | ForEach-Object {
        "            <desktop5:ItemType Type=`".$_`"><desktop5:Verb Id=`"TumbleConvert`" Clsid=`"$clsid`" /></desktop5:ItemType>"
    }) -join "`n"
    $version = (Select-String -Path (Join-Path $repo 'Cargo.toml') -Pattern '^version = "(.+)"').Matches[0].Groups[1].Value
    @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/explorer/scripts/explorer-menu.ps1. -->
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
         xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
         xmlns:uap10="http://schemas.microsoft.com/appx/manifest/uap/windows10/10"
         xmlns:desktop4="http://schemas.microsoft.com/appx/manifest/desktop/windows10/4"
         xmlns:desktop5="http://schemas.microsoft.com/appx/manifest/desktop/windows10/5"
         xmlns:com="http://schemas.microsoft.com/appx/manifest/com/windows10"
         xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
         IgnorableNamespaces="uap uap10 desktop4 desktop5 com rescap">
  <Identity Name="$packageName" Publisher="$publisher" Version="$version.0" ProcessorArchitecture="x64" />
  <Properties>
    <DisplayName>Tumble</DisplayName>
    <PublisherDisplayName>Tumble</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
    <uap10:AllowExternalContent>true</uap10:AllowExternalContent>
  </Properties>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.22000.0" MaxVersionTested="10.0.26300.0" />
  </Dependencies>
  <Resources>
    <Resource Language="en-us" />
  </Resources>
  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="unvirtualizedResources" />
  </Capabilities>
  <Applications>
    <Application Id="Tumble" Executable="tumblew.exe" uap10:TrustLevel="mediumIL" uap10:RuntimeBehavior="win32App">
      <uap:VisualElements AppListEntry="none" DisplayName="Tumble" Description="Convert files from the right-click menu"
                          BackgroundColor="transparent" Square150x150Logo="Assets\Square150x150Logo.png"
                          Square44x44Logo="Assets\Square44x44Logo.png" />
      <Extensions>
        <desktop4:Extension Category="windows.fileExplorerContextMenus">
          <desktop4:FileExplorerContextMenus>
$itemTypes
          </desktop4:FileExplorerContextMenus>
        </desktop4:Extension>
        <com:Extension Category="windows.comServer">
          <com:ComServer>
            <com:SurrogateServer DisplayName="Tumble Explorer menu">
              <com:Class Id="$clsid" Path="tumble_explorer.dll" ThreadingModel="STA" />
            </com:SurrogateServer>
          </com:ComServer>
        </com:Extension>
      </Extensions>
    </Application>
  </Applications>
</Package>
"@ | Set-Content (Join-Path $pkg 'AppxManifest.xml') -Encoding utf8

    Write-Host '== packing'
    & (Join-Path $sdk 'makeappx.exe') pack /d $pkg /p $msix /nv /o | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'makeappx failed' }

    if (-not (Test-Path $pfx)) {
        Write-Host '== creating a self-signed code-signing certificate (in memory, no store)'
        $rsa = [Security.Cryptography.RSA]::Create(3072)
        $req = [Security.Cryptography.X509Certificates.CertificateRequest]::new(
            $publisher, $rsa, [Security.Cryptography.HashAlgorithmName]::SHA256,
            [Security.Cryptography.RSASignaturePadding]::Pkcs1)
        $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($false, $false, 0, $true))
        $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new(
            [Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature, $true))
        $eku = [Security.Cryptography.OidCollection]::new()
        [void]$eku.Add([Security.Cryptography.Oid]::new('1.3.6.1.5.5.7.3.3'))   # code signing
        $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension]::new($eku, $false))
        $cert = $req.CreateSelfSigned([DateTimeOffset]::Now.AddDays(-1), [DateTimeOffset]::Now.AddYears(3))
        [IO.File]::WriteAllBytes($pfx, $cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pfx))
        [IO.File]::WriteAllBytes($cer, $cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    }
    Write-Host '== signing'
    & (Join-Path $sdk 'signtool.exe') sign /q /fd SHA256 /f $pfx $msix
    if ($LASTEXITCODE -ne 0) { throw 'signtool failed' }
    Write-Host "== built $msix"
    Write-Host "   external location: $AppDir"
}

function Test-Admin {
    ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
}

switch ($Action) {
    'build' { Build }
    'install' {
        if (-not (Test-Path $msix)) { throw 'Run with -Action build first.' }
        $thumb = ([Security.Cryptography.X509Certificates.X509Certificate2]::new($cer)).Thumbprint
        if (-not (Test-Path "Cert:\LocalMachine\TrustedPeople\$thumb")) {
            if (-not (Test-Admin)) {
                throw "The package certificate is not trusted yet. Run this in an elevated terminal (it trusts $cer for package installs only)."
            }
            Import-Certificate -FilePath $cer -CertStoreLocation Cert:\LocalMachine\TrustedPeople | Out-Null
            Write-Host "Trusted $cer in LocalMachine\TrustedPeople"
        }
        Get-AppxPackage -Name $packageName | Remove-AppxPackage
        Add-AppxPackage -Path $msix -ExternalLocation $AppDir
        Write-Host 'Installed. Right-click a supported file: "Convert to" is now in the main Windows 11 menu.'
        Write-Host 'If it does not show yet, restart Explorer (Task Manager > Windows Explorer > Restart).'
    }
    'uninstall' {
        Get-AppxPackage -Name $packageName | Remove-AppxPackage
        Write-Host 'Package removed.'
        if (Test-Path $cer) {
            $thumb = ([Security.Cryptography.X509Certificates.X509Certificate2]::new($cer)).Thumbprint
            if (Test-Path "Cert:\LocalMachine\TrustedPeople\$thumb") {
                if (Test-Admin) {
                    Remove-Item "Cert:\LocalMachine\TrustedPeople\$thumb"
                    Write-Host 'Certificate removed from TrustedPeople.'
                } else {
                    Write-Host "Certificate still trusted; to remove it, run elevated: Remove-Item Cert:\LocalMachine\TrustedPeople\$thumb"
                }
            }
        }
    }
}
